name: Deploy (devel)
concurrency: pages_deployment

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: development
    env:
      IS_DEVEL: true
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: yarn

    - run: corepack enable
    - run: yarn install --frozen-lockfile

    - run: yarn typecheck
    - run: yarn lint

    - run: yarn build
      env:
        BCX_SAVE_AUTH: ${{ secrets.BCX_SAVE_AUTH }}

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: ./dist
        destination_dir: devel
        keep_files: true
